// create Calculator by   Wrapper class and test class with assert usage and also i have to focus 
//on value is postive or negative.
 public class WrapperCalculator {
    Public static void WrapperclassMethod()
        {
            Decimal num1;
            Decimal num2;
            
            
  Decimal sum =num1+num2;
            if( sum>=0){
                system.Debug('The sum of two number is positive'+ sum);
            }
  Decimal  sub =num1-num2;
            if( sub>=0){
                system.Debug('The sub of two number is positive'+ sub);
            }
          Decimal mul=num1*num2;
            if (mul>=0){
                system.Debug('The Multiplication of two number is positive'+ mul);
            }
        
    Decimal  Div=num1/num2;
            if( Div>=0){
                system.Debug('The Division of two number is positive'+ Div);
            }
        }
    
}